# Generated by Django 3.1 on 2020-08-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('machine_1', models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0)),
            ],
        ),
    ]
