# Generated by Django 3.1 on 2020-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='machine_2',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='machine_3',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='machine_4',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
    ]
