# Generated by Django 3.1 on 2020-08-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20200830_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='photos/default-photo.png', upload_to='photos/'),
        ),
    ]
