# Generated by Django 3.1 on 2020-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20200830_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='machine_5',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
    ]
