# Generated by Django 3.1.2 on 2020-10-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('level_1', models.TextField(max_length=1000)),
                ('level_2', models.TextField(max_length=1000)),
                ('level_3', models.TextField(max_length=1000)),
                ('level_4', models.TextField(max_length=1000)),
            ],
        ),
    ]
