# Generated by Django 3.1.2 on 2020-10-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level_1',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='level_2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='level_3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='level_4',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
