# Generated by Django 3.1.2 on 2020-10-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20201013_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assembly',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='cnc_lathe',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='cnc_mill',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='drill',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='engineering',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='epoxy',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='fuse',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='laser',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='powder_coat',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='press_brake',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='quality',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='robot_weld',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='shipping',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='stamp',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='water_jet',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='weld',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
    ]
