# Generated by Django 3.1 on 2021-10-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_auto_20201029_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ju_channel',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='maintenance',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='saw',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Novice'), (4, 'Expert')], default=0),
        ),
    ]
